excerpt_separator: ""
#pygments: true
highlighter: rouge
markdown: kramdown
url: http://gapzroble.github.io
title: gapz101
tagline: logger
description: My awesome new site
paginate: 5

theme: jekyll-theme-slate
